name: pioneers_smartsave

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.5
  provider: ^6.1.0
  flutter_bloc: ^9.1.0
  get: ^4.6.5
  intl: ^0.19.0
  http: ^1.3.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  flutter_secure_storage: ^8.0.0
  dio: ^5.4.0
  image_picker: ^1.1.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#     - assets/icons/
#     - assets/fonts/
#   fonts:
#     - family: Montserrat
#       fonts:
#         - asset: assets/fonts/Montserrat-Regular.ttf
#         - asset: assets/fonts/Montserrat-Bold.ttf
#           weight: 700
#         - asset: assets/fonts/Montserrat-Italic.ttf
#           style: italic
#         - asset: assets/fonts/Montserrat-BoldItalic.ttf
#           weight: 700
#           style: italic