// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzuW5AsK6suP0LG8zfGxl9NxMN7mZ5Oc',
    appId: '1:992191879468:web:c9b3f121f4ee8b9bf93489',
    messagingSenderId: '992191879468',
    projectId: 'pioneers-smartsave',
    authDomain: 'pioneers-smartsave.firebaseapp.com',
    storageBucket: 'pioneers-smartsave.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbNBl_3fL3QW8dvIQzyaXUtjtjuShqXg',
    appId: '1:992191879468:android:0326f4cb0c324b11f93489',
    messagingSenderId: '992191879468',
    projectId: 'pioneers-smartsave',
    storageBucket: 'pioneers-smartsave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmTvX2m8l1LOk7NW_8iKOGvFKec-_WAU',
    appId: '1:992191879468:ios:b29cc71cb91cf27bf93489',
    messagingSenderId: '992191879468',
    projectId: 'pioneers-smartsave',
    storageBucket: 'pioneers-smartsave.firebasestorage.app',
    iosBundleId: 'com.example.pioneersSmartsave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtmTvX2m8l1LOk7NW_8iKOGvFKec-_WAU',
    appId: '1:992191879468:ios:b29cc71cb91cf27bf93489',
    messagingSenderId: '992191879468',
    projectId: 'pioneers-smartsave',
    storageBucket: 'pioneers-smartsave.firebasestorage.app',
    iosBundleId: 'com.example.pioneersSmartsave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYzuW5AsK6suP0LG8zfGxl9NxMN7mZ5Oc',
    appId: '1:992191879468:web:a1343578c843b935f93489',
    messagingSenderId: '992191879468',
    projectId: 'pioneers-smartsave',
    authDomain: 'pioneers-smartsave.firebaseapp.com',
    storageBucket: 'pioneers-smartsave.firebasestorage.app',
  );

}